#! /bin/sh
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch skip --weight_init uniform
/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch ResNet --weight_init uniform
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch UNet --weight_init uniform
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch skip --weight_init normal
/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch ResNet --weight_init normal
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch UNet --weight_init normal
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch skip --weight_init constant
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch ResNet --weight_init constant
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch UNet --weight_init constant
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch skip --weight_init xavier_uniform
/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch ResNet --weight_init xavier_uniform
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch UNet --weight_init xavier_uniform
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch skip --weight_init xavier_normal
/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch ResNet --weight_init xavier_normal
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch UNet --weight_init xavier_normal
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch skip --weight_init kaiming_uniform
/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch ResNet --weight_init kaiming_uniform
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch UNet --weight_init kaiming_uniform
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch skip --weight_init kaiming_normal
/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch ResNet --weight_init kaiming_normal
#/usr/bin/python3.5 /home/osherm/PycharmProjects/deep-image-prior/super-resolution.py --file_path data/sr/parrot2.jpg --net_arch UNet --weight_init kaiming_normal
